version: "3"

services:
  indoorapp:
    container_name: indoorapp-cont
    environment:
      - PASSWORD=ubuntu
    volumes:
      - ./data:/app/data
      - ./processed_data:/app/processed_data

    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

volumes:
  data:
  processed_data:
